### ISSUE TITLE
Error running startup.sh

### ISSUE THREAD

**Issue by kterah** [informatici/openhospital#140]
I am on Ubuntu 2004, using mysql 8.0.21, and openjdk version 1.8.0_265. I downloaded openhospital 1.10.0. I got the db import to complete cleanly. But everytime 

I run startup.sh I get: 
```
kaggwat@djit-004:~/OpenHospital-1.10.0$ ./startup.sh 
[14/Oct/2020 16:23:32] [:] INFO - HCANN000001: Hibernate Commons Annotations {4.0.2.Final}
[14/Oct/2020 16:23:32] [:] INFO - HHH000412: Hibernate Core {4.2.13.Final}
[14/Oct/2020 16:23:32] [:] INFO - HHH000206: hibernate.properties not found
[14/Oct/2020 16:23:32] [:] INFO - HHH000021: Bytecode provider name : javassist
[14/Oct/2020 16:23:32] [:] INFO - HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
[14/Oct/2020 16:23:32] [:] INFO - HHH000130: Instantiating explicit connection provider: org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider
[14/Oct/2020 16:24:02] [:] WARN - HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database!
[14/Oct/2020 16:24:02] [:] INFO - HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
[14/Oct/2020 16:24:02] [:] INFO - HHH000422: Disabling contextual LOB creation as connection was null
[14/Oct/2020 16:24:03] [:] INFO - HHH000268: Transaction strategy: org.hibernate.engine.transaction.internal.jdbc.JdbcTransactionFactory
[14/Oct/2020 16:24:03] [:] INFO - HHH000397: Using ASTQueryTranslatorFactory
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
	at org.isf.menu.gui.Menu.main(Menu.java:59)
```

This is a testing environment so I have gone with defaults for the database.properties:
```
jdbc.url="jdbc:mysql://localhost:3306/oh"
jdbc.username=isf
jdbc.password=isf123
```

Java details:
There are 2 choices for the alternative java (providing /usr/bin/java).
```
  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 
kaggwat@djit-004:~/OpenHospital-1.10.0$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
kaggwat@djit-004:~/OpenHospital-1.10.0$ javac -version
javac 1.8.0_265
```

Where could this failing from? Please assist.

Thank you
Terah

**Comment by kterah** [comment]
Thanks @mwithi, 

I have done so and now getting past that point. However I then get a popup saying 'Problems occured with server connection" with only OK button. In terminal I have:

=====================
Starting OpenHospital
=====================

[14/Oct/2020 17:31:17] [:] INFO - OpenHospital version 1.10.0
[14/Oct/2020 17:31:17] [:] INFO - Java version 1.8.0_265
[14/Oct/2020 17:31:20] [:] INFO - File generalData.properties loaded. 
[14/Oct/2020 17:31:20] [:] INFO - Logging: Single User mode.
[14/Oct/2020 17:31:50] [admin:admin] WARN - SQL Error: 0, SQLState: null
[14/Oct/2020 17:31:50] [admin:admin] ERROR - Connections could not be acquired from the underlying database!

I also notice in my earlier message it says, and still says:

WARN - HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database!

Any advice on this?

Thank you

Terah

**Comment by mwithi** [comment]
Hi @kterah, I'm glad you solved the problem, but we coudl help other users if you share exactly what you did.

For the new connection error, simply it is not finding the server... did you follow the [Admin Manual](https://github.com/informatici/openhospital-doc/blob/develop/doc_admin/AdminManual.adoc) instructions?

**Comment by mwithi** [comment]
Also, please format terminal output and commands with the code format (check how I've modified your comments)

![image](https://user-images.githubusercontent.com/2938553/96005958-45b1b480-0e3d-11eb-9991-b89b747d0cdd.png)

Thanks!

**Comment by kterah** [comment]
Hello,

Solution was to remove headless versions of openjdk-8, on ubuntu:

apt remove openjdk-8-jre-headless

then: 

apt remove openjdk-8-jre

Thanks

Terah

**Comment by mwithi** [comment]
Thanks you too Terah! 

You close the issue: did you solve the connection problem? What was the problem for the other users sake?

**Comment by kterah** [comment]
Hello

**Comment by kterah** [comment]
Hello,

My bad. That was unintended. My connection problem persists. I thought OH gets connection details from rsc/database.properties which looks OK. I can ping and telnet to the port 3306 but this is still failing. Have attached the image ...

Any advice?

Thanks

Terah

![oh](https://user-images.githubusercontent.com/52583383/96009133-f7a2ae00-0e48-11eb-898f-8cf34b0b8a42.png)

**Comment by kterah** [comment]
This is what I get am using defaults everything - including username and passwd.

Thanks

Terah

![oh2](https://user-images.githubusercontent.com/52583383/96024462-6dfcdb80-0e5c-11eb-8f7c-a11f3481b1a9.png)

**Comment by kterah** [comment]
Hello,

So I had to download the java connector for mysql8 from the oracle site and install it. Then adjusted classpath to add its location:

export CLASSPATH=/usr/share/java/mysql-connector-java-8.0.21.jar:$CLASSPATH

Looks like the connector I had was old and couldn't work with the mysql I was using. After the above, it all came up good.

Thank you

Terah

**Comment by mwithi** [comment]
Yes, probably it's because you was using MySQL Server 8+, while the doc for [v1.10.0](https://github.com/informatici/openhospital-doc/blob/v1.10.0/doc_admin/AdminManual.adoc#3-1-1-java-runtime-environment) (this link replace the previous one) is suggesting to use:
- MySQL Server 5.0.x
- Java6 32bit for full compliance

Anyway for testing environment you can proceed as you did (congrats!), soon will be release **v1.11.0** which will support Java8 and MySQL 5.7+, with also mysql-connector-java-8 ([see wip](https://github.com/informatici/openhospital-core/blob/OP-282-101_Spring5_and_Java8_time/pom.xml#L253))

Thanks a lot for the feedback!

**Comment by mwithi** [comment]
Updated [Wiki](https://openhospital.atlassian.net/wiki/spaces/OH/pages/568951013/Getting+Started+FAQ) with this two errors.

Thanks a lot!
