### ISSUE TITLE
exception opening DICOM 

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#57]
POH on windows with no particular hardware attached.
I wanted to load a Dicom image to test https://github.com/informatici/openhospital-doc/blob/master/doc_user/UserManual.adoc#1091-dicom-dicom-viewer

On clicking the DICOM button I get

![Schermata 2020-02-11 alle 12 16 30](https://user-images.githubusercontent.com/1875906/74232444-186aa080-4cc9-11ea-8ba9-84423362bf8e.jpg)

But I can then proceed to load a dicom file
The file I use is just a sample found in http://www.rubomedical.com/dicom_files/ named http://www.rubomedical.com/dicom_files/dicom_viewer_0002.zip
I don't know if the file has any problem within but after clicking open I get

Exception in thread "AWT-EventQueue-1" java.lang.NoClassDefFoundError: com/sun/m
edia/imageio/stream/StreamSegmentMapper
        at org.dcm4che2.imageioimpl.plugins.dcm.DicomImageReaderSpi.createReaderInstance(DicomImageReaderSpi.java:146)
        at javax.imageio.spi.ImageReaderSpi.createReaderInstance(Unknown Source)
        at javax.imageio.ImageIO$ImageReaderIterator.next(Unknown Source)
        at javax.imageio.ImageIO$ImageReaderIterator.next(Unknown Source)
        at org.isf.dicom.manager.SourceFiles.loadDicom(SourceFiles.java:116)
        at org.isf.dicom.gui.DicomGui$1.actionPerformed(DicomGui.java:274)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$400(Unknown Source)
        at java.awt.EventQueue$2.run(Unknown Source)
        at java.awt.EventQueue$2.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(UnknownSource)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(UnknownSource)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessControlContext$1.doIntersectionPrivilege(UnknownSource)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at org.isf.utils.jobjects.WaitCursorEventQueue.dispatchEvent(WaitCursorEventQueue.java:24)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.media.imageio.stream.StreamSegmentMapper
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 43 more

and nothing is rendered

**Comment by mwithi** [comment]
Thank you @virivigio for the notification, it's a known problem due to missing recent compatible libraries, the bug is addressed in task **[OP-140](https://openhospital.atlassian.net/projects/OP/issues/OP-140)** and already under study.

**Comment by mwithi** [comment]
Fixed with https://github.com/informatici/openhospital-core/pull/56
